name: pos_cashier
description: "POS Cashier Application - Offline-capable point of sale system"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  animations: ^2.0.11
  shimmer: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.2

  # Local Database (Offline Support)
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3
  sqlite3_flutter_libs: ^0.5.24
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5

  # Network (Minimal for sync)
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  pretty_dio_logger: ^1.4.0

  # Authentication
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.3.3

  # Background Sync
  workmanager: ^0.5.2
  rxdart: ^0.28.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1

  # Barcode Scanner
  mobile_scanner: ^5.2.3
  qr_flutter: ^4.1.0

  # Printing
  pdf: ^3.11.1
  printing: ^5.13.4

  # Utils
  dartz: ^0.10.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
