name: pos_management
description: "POS Management Application - Online-only management and analytics system"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  animations: ^2.0.11
  shimmer: ^3.0.0

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.2

  # Cache (Settings only, NO offline data)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # Network (Full featured - ONLINE ONLY)
  dio: ^5.7.0
  connectivity_plus: ^6.1.0
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^2.0.3+1

  # Authentication & Security
  jwt_decoder: ^2.0.1
  crypto: ^3.0.6

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  path_provider: ^2.1.5

  # Excel Export
  excel: ^4.0.6

  # PDF Generation
  pdf: ^3.11.1
  printing: ^5.13.4

  # File Picker
  file_picker: ^8.1.6

  # Image
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Utils
  dartz: ^0.10.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/logos/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
